### ISSUE TITLE
App doesn't launch

### ISSUE THREAD

**Issue by shickey** [BlakeCS-Spring2015/Bakken-Prototype#3]
Splash screen appears, then crashes on startup. SIGABRT. This probably is related to merge things

**Comment by weinshel** [comment]
Fixed in b82bde2

There were a couple of issues here. Firstly, `ObjectSelectTableViewController` was renamed to `ObjectSelectCollectionViewController`, so all the references had to be updated. Also, I had to add `ObjectSelectCollectionViewController.m` to the build phase.

Still having navbar and timeout issues
